### PR TITLE
Improve the landing page photo

### PR DESCRIPTION
**Pull request by matthewgrossman**
Prior photo was trying to capture the "moment it all happened", but I think this one is better

### CODE REVIEW

**Comment by matthewgrossman** [comment]
ptal @guyman575 @leahcschatz

**Comment by matthewgrossman** [comment]
note: this is a blocker before public launch of the site

**Comment by guyman575** [comment]
No.

**Comment by vrchen** [comment]
bump, why was this PR closed? i thought it was a blocker before public launch.

**Comment by connormason** [comment]
+1 

The fact that this PR was closed means that the maintainers clearly do not respect the desires of the greater developer community. Very closed-source state of mind it seems

**Comment by matthewgrossman** [comment]
I wanna say we won in the end

**Pull request closed without merging**
